import pathlib
import os

char_labels = [
     "Aliff", 
     "Aliff End", 
     "Bey", 
     "Bey Begin", 
     "Bey Middle", 
     "Bey End", 
     "Pay", 
     "Pay Begin", 
     "Pay Middle", 
     "Pay End", 
     "Tae", 
     "Tae Begin", 
     "Tae Middle", 
     "Tae End", 
     "Ttay", 
     "Ttay Begin", 
     "Ttay Middle", 
     "Ttay End", 
     "Say", 
     "Say Begin", 
     "Say Middle", 
     "Say End", 
     "Jeem", 
     "Jeem Begin", 
     "Jeem Middle", 
     "Jeem End", 
     "Cheem", 
     "Cheem Begin", 
     "Cheem Middle", 
     "Cheem End", 
     "Hi", 
     "Hi Begin", 
     "Hi Middle", 
     "Hi End", 
     "Khai", 
     "Khai Begin", 
     "Khai Middle", 
     "Khai End", 
     "Daal", 
     "Daal End", 
     "Dhaal", 
     "Dhaal End", 
     "Zaal", 
     "Zaal End", 
     "Ray End", 
     "Day End", 
     "Zay", 
     "Czay End", 
     "Seen", 
     "Seen Begin", 
     "Sheen Middle", 
     "Sheen End", 
     "Soad", 
     "Soad Begin", 
     "Soad Middle", 
     "Soad End", 
     "Doad", 
     "Doad Begin", 
     "Doad Middle", 
     "Doad End", 
     "Toi", 
     "Toi End", 
     "Zoi", 
     "Zoi End", 
     "Ayn", 
     "Ayn Begin", 
     "Ayn Middle", 
     "Ayn End", 
     "Gain", 
     "Gain Begin", 
     "Gain Middle", 
     "Gain End", 
     "Fay", 
     "Fay Begin", 
     "Fay Middle", 
     "Fay End", 
     "Qaaf", 
     "Qaaf Begin", 
     "Qaaf Middle", 
     "Qaaf End", 
     "Keef", 
     "Keef Begin", 
     "Keef Middle", 
     "Keef End", 
     "Gaaf", 
     "Gaaf Begin", 
     "Gaaf Middle", 
     "Gaaf End", 
     "Laam", 
     "Laam Begin", 
     "Laam Middle", 
     "Laam End", 
     "Meem", 
     "Meem Begin", 
     "Meem Middle", 
     "Meem End", 
     "Noon", 
     "Noon Begin", 
     "Noon Middle", 
     "Noon End", 
     "Waav", 
     "Waav End", 
     "Hay", 
     "Hay Begin", 
     "Hay Middle", 
     "Hay End 2", 
     "Do Chasm Begin", 
     "Do Chasm End", 
     "Hamza", 
     "Chota Yay", 
     "Chota Yay Begin", 
     "Chota Yay Middle", 
     "Bada Yay", 
     "Aliff Madd", 
     "Noon Gunnah", 
     "Noon Gunnah End", 
     "Zero", 
     "One", 
     "Two", 
     "Three", 
     "Four", 
     "Five", 
     "Six", 
     "Seven", 
     "Eight", 
     "Nine"
]

main_dir = pathlib.Path(__file__).parent.absolute()
model_1_dir='saved_model'
model_2_dir='saved_model_again' 
model_file_abs_path = os.path.join(main_dir, 'trained_models', model_1_dir, 'my_model')
images_dir_abs_path = os.path.join(main_dir, 'images')